// SPDX-License-Identifier: GPL-3.0-or-later
//
// ps2.cpp — PS/2 host driver implementation for RP2040 (PIO-based)
//
// Copyright (C) 2026 Arnav
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

#include "ps2.hpp"
#include "ps2.pio.h"  // auto-generated by pico_generate_pio_header()

#include "hardware/clocks.h"
#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "pico/stdlib.h"
#include "pico/time.h"

#include <cstdio>

// PS/2 protocol constants
static constexpr uint8_t PS2_ACK        = 0xFA;
static constexpr uint8_t PS2_SELF_TEST  = 0xAA;
static constexpr uint8_t PS2_CMD_RESET  = 0xFF;
static constexpr uint8_t PS2_CMD_RESEND = 0xFE;
static constexpr uint8_t PS2_CMD_ENABLE = 0xF4;
static constexpr uint8_t PS2_CMD_DISABLE = 0xF5;
static constexpr uint8_t PS2_CMD_SET_RES = 0xE8;
static constexpr uint8_t PS2_CMD_STATUS_REQ = 0xE9;
static constexpr uint8_t PS2_CMD_SET_RATE = 0xF3;

// ---------------------------------------------------------------------------
// Constructor
// ---------------------------------------------------------------------------

PS2::PS2(PIO pio, uint sm, uint data_pin, uint clk_pin)
    : pio_(pio), sm_(sm), data_pin_(data_pin), clk_pin_(clk_pin),
      pio_offset_(0), is_synaptics_absolute_(false) {}

// ---------------------------------------------------------------------------
// init — load PIO program, configure pins, start state machine
// ---------------------------------------------------------------------------

void PS2::init() {
    // Configure DATA and CLK pins as inputs with pull-ups.
    // PS/2 is open-drain; we only ever drive LOW or float (input).
    gpio_init(data_pin_);
    gpio_init(clk_pin_);
    gpio_set_dir(data_pin_, GPIO_IN);
    gpio_set_dir(clk_pin_, GPIO_IN);
    gpio_pull_up(data_pin_);
    gpio_pull_up(clk_pin_);

    // Load the PIO program
    pio_offset_ = pio_add_program(pio_, &ps2_rx_program);

    // Configure the state machine
    pio_sm_config c = ps2_rx_program_get_default_config(pio_offset_);

    // IN pins: base = data_pin_ (pin 0 = DATA, pin 1 = CLK)
    sm_config_set_in_pins(&c, data_pin_);

    // Shift ISR to the right, no autopush — we push manually in PIO
    sm_config_set_in_shift(&c, true, false, 8);

    // SM clock: 200 kHz is plenty for the ~10-16 kHz PS/2 clock.
    // Each PIO instruction takes 1 cycle, and `wait` instructions poll
    // every cycle, so 200 kHz gives us ~12-20 samples per PS/2 clock period.
    float div = (float)clock_get_hz(clk_sys) / 200000.0f;
    sm_config_set_clkdiv(&c, div);

    // Join FIFOs for RX only (we don't use TX FIFO in PIO)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);

    // Initialize and enable the state machine
    pio_sm_init(pio_, sm_, pio_offset_, &c);
    pio_sm_set_enabled(pio_, sm_, true);
}

// ---------------------------------------------------------------------------
// flush_rx — drain stale data from the PIO RX FIFO
// ---------------------------------------------------------------------------

void PS2::flush_rx() {
    while (!pio_sm_is_rx_fifo_empty(pio_, sm_)) {
        (void)pio_sm_get(pio_, sm_);
    }
}

// ---------------------------------------------------------------------------
// recv_byte — read one byte from the PIO RX FIFO with timeout
// ---------------------------------------------------------------------------

bool PS2::recv_byte(uint8_t &out, uint32_t timeout_ms) {
    absolute_time_t deadline = make_timeout_time_ms(timeout_ms);

    while (pio_sm_is_rx_fifo_empty(pio_, sm_)) {
        if (absolute_time_diff_us(get_absolute_time(), deadline) <= 0) {
            return false;  // timed out
        }
        tight_loop_contents();
    }

    // The PIO pushed 8 data bits shifted right into a 32-bit word.
    // The 8 data bits sit in bits [31:24] because we shifted right
    // with autopush disabled and push_thresh=8 is not set (manual push).
    // Actually with in_shift_right and manual push after 8 bits,
    // the data lands in the upper bits. We need to shift it down.
    uint32_t raw = pio_sm_get(pio_, sm_);
    out = (uint8_t)(raw >> 24);
    return true;
}

// ---------------------------------------------------------------------------
// send_byte — host-to-device PS/2 transmission (bit-bang)
//
// Protocol:
//   1. Host pulls CLK LOW for at least 100 us (inhibit / request-to-send)
//   2. Host pulls DATA LOW (start bit)
//   3. Host releases CLK
//   4. Device generates clock; host shifts out 8 data bits + parity + stop
//      on each CLK falling edge
//   5. Device sends ACK by pulling DATA LOW on the last clock cycle
//
// We temporarily disable the PIO state machine during transmission.
// ---------------------------------------------------------------------------

bool PS2::send_byte(uint8_t data) {
    // Disable PIO SM so it doesn't interfere
    pio_sm_set_enabled(pio_, sm_, false);

    // Calculate odd parity
    uint8_t parity = 1;
    for (int i = 0; i < 8; i++) {
        parity ^= (data >> i) & 1;
    }

    // Deadline for the entire send sequence (50ms is very generous;
    // a PS/2 frame at 10 kHz clock takes ~1.1 ms)
    absolute_time_t deadline = make_timeout_time_ms(50);

    // Helper: wait for a pin to reach a target state, with timeout.
    // Returns false if the deadline expires.
    auto wait_pin = [&](uint pin, bool state) -> bool {
        while (gpio_get(pin) != state) {
            if (absolute_time_diff_us(get_absolute_time(), deadline) <= 0) {
                return false;
            }
            tight_loop_contents();
        }
        return true;
    };

    // Step 1: Pull CLK LOW for ~150 us (request-to-send)
    gpio_set_dir(clk_pin_, GPIO_OUT);
    gpio_put(clk_pin_, 0);
    sleep_us(150);

    // Step 2: Pull DATA LOW (start bit)
    gpio_set_dir(data_pin_, GPIO_OUT);
    gpio_put(data_pin_, 0);

    // Step 3: Release CLK (set to input, pull-up brings it HIGH)
    gpio_set_dir(clk_pin_, GPIO_IN);
    gpio_pull_up(clk_pin_);

    // Step 4: Wait for device to clock in each bit (8 data + 1 parity + 1 stop)
    // The device drives CLK; we change DATA on each CLK falling edge.
    bool ok = true;
    for (int i = 0; i < 8 && ok; i++) {
        ok = wait_pin(clk_pin_, false);         // CLK falling edge
        if (ok) gpio_put(data_pin_, (data >> i) & 1);
        if (ok) ok = wait_pin(clk_pin_, true);  // CLK rising edge
    }

    // Send parity bit
    if (ok) ok = wait_pin(clk_pin_, false);
    if (ok) gpio_put(data_pin_, parity);
    if (ok) ok = wait_pin(clk_pin_, true);

    // Send stop bit (HIGH = release DATA)
    if (ok) ok = wait_pin(clk_pin_, false);
    if (ok) {
        gpio_set_dir(data_pin_, GPIO_IN);
        gpio_pull_up(data_pin_);
    }
    if (ok) ok = wait_pin(clk_pin_, true);

    // Wait for device ACK: device pulls DATA LOW, then one more clock cycle
    bool ack = false;
    if (ok) ok = wait_pin(clk_pin_, false);
    if (ok) ack = !gpio_get(data_pin_);  // DATA should be LOW (ACK from device)
    if (ok) ok = wait_pin(clk_pin_, true);

    // Wait for device to release both lines (with timeout)
    if (ok) {
        while (!gpio_get(data_pin_) || !gpio_get(clk_pin_)) {
            if (absolute_time_diff_us(get_absolute_time(), deadline) <= 0) {
                ok = false;
                break;
            }
            tight_loop_contents();
        }
    }

    if (!ok) {
        // Timed out — make sure pins are released before re-enabling PIO
        gpio_set_dir(data_pin_, GPIO_IN);
        gpio_pull_up(data_pin_);
        gpio_set_dir(clk_pin_, GPIO_IN);
        gpio_pull_up(clk_pin_);
        printf("[PS2] send_byte(0x%02X): timed out\n", data);
    }

    // Re-enable PIO SM for receiving
    // First reset the SM so it starts fresh from the beginning of the program
    pio_sm_clear_fifos(pio_, sm_);
    pio_sm_restart(pio_, sm_);
    pio_sm_exec(pio_, sm_, pio_encode_jmp(pio_offset_));
    pio_sm_set_enabled(pio_, sm_, true);

    return ack;
}

// ---------------------------------------------------------------------------
// command — send a command byte, wait for ACK
// ---------------------------------------------------------------------------

bool PS2::command(uint8_t cmd) {
    flush_rx();
    if (!send_byte(cmd)) {
        return false;
    }
    uint8_t response;
    if (!recv_byte(response, 200)) {
        return false;
    }
    return response == PS2_ACK;
}

// ---------------------------------------------------------------------------
// command — send command + argument, wait for ACK after each
// ---------------------------------------------------------------------------

bool PS2::command(uint8_t cmd, uint8_t arg) {
    if (!command(cmd)) {
        return false;
    }
    return command(arg);
}

// ---------------------------------------------------------------------------
// reset — send 0xFF, read ACK + self-test (0xAA) + device ID
// ---------------------------------------------------------------------------

bool PS2::reset(uint8_t &device_id) {
    flush_rx();

    if (!send_byte(PS2_CMD_RESET)) {
        printf("[PS2] Reset: send_byte failed\n");
        return false;
    }

    uint8_t response;

    // Read ACK (0xFA)
    if (!recv_byte(response, 500)) {
        printf("[PS2] Reset: no ACK\n");
        return false;
    }
    if (response != PS2_ACK) {
        printf("[PS2] Reset: expected ACK (0xFA), got 0x%02X\n", response);
        return false;
    }

    // Read self-test result (0xAA = pass)
    // The device may take up to 500ms to complete self-test
    if (!recv_byte(response, 1000)) {
        printf("[PS2] Reset: no self-test result\n");
        return false;
    }
    if (response != PS2_SELF_TEST) {
        printf("[PS2] Reset: self-test failed (0x%02X)\n", response);
        return false;
    }

    // Read device ID (0x00 for standard mouse)
    if (!recv_byte(device_id, 500)) {
        printf("[PS2] Reset: no device ID\n");
        return false;
    }

    return true;
}

// ---------------------------------------------------------------------------
// enable_reporting / disable_reporting
// ---------------------------------------------------------------------------

bool PS2::enable_reporting() {
    return command(PS2_CMD_ENABLE);
}

bool PS2::disable_reporting() {
    return command(PS2_CMD_DISABLE);
}

// ---------------------------------------------------------------------------
// read_packet — read and decode a 3-byte standard PS/2 mouse packet
//
// Byte 0: [Y_OVF | X_OVF | Y_SIGN | X_SIGN | 1 | MID | RIGHT | LEFT]
// Byte 1: X movement (unsigned, sign in byte 0 bit 4)
// Byte 2: Y movement (unsigned, sign in byte 0 bit 5)
// ---------------------------------------------------------------------------

bool PS2::read_packet(Packet &pkt, uint32_t timeout_ms) {
    uint8_t buf[3];

    if (!recv_byte(buf[0], timeout_ms)) {
        return false;
    }

    // Validate: bit 3 of byte 0 should always be 1 in a standard PS/2 packet.
    // If it's not, we're out of sync. Actively resync by scanning incoming
    // bytes until we find one with bit 3 set, then use it as byte 0.
    if (!(buf[0] & 0x08)) {
        static constexpr int MAX_RESYNC = 11;  // at most one full packet of junk
        bool synced = false;
        for (int i = 0; i < MAX_RESYNC; i++) {
            uint8_t candidate;
            if (!recv_byte(candidate, timeout_ms)) {
                return false;
            }
            if (candidate & 0x08) {
                buf[0] = candidate;
                synced = true;
                printf("[PS2] Resync: skipped %d byte(s)\n", i + 1);
                break;
            }
        }
        if (!synced) {
            flush_rx();
            printf("[PS2] Resync failed — flushed RX FIFO\n");
            return false;
        }
    }

    // Read remaining 2 bytes
    for (int i = 1; i < 3; i++) {
        if (!recv_byte(buf[i], timeout_ms)) {
            return false;
        }
    }

    pkt.left       = buf[0] & 0x01;
    pkt.right      = (buf[0] >> 1) & 0x01;
    pkt.middle     = (buf[0] >> 2) & 0x01;
    pkt.x_overflow = (buf[0] >> 6) & 0x01;
    pkt.y_overflow = (buf[0] >> 7) & 0x01;

    // Sign-extend X and Y using the sign bits in byte 0
    pkt.dx = buf[1] - ((buf[0] & 0x10) ? 256 : 0);
    pkt.dy = buf[2] - ((buf[0] & 0x20) ? 256 : 0);

    return true;
}

// ---------------------------------------------------------------------------
// synaptics_identify — Send E8 sequence to query identity
// ---------------------------------------------------------------------------

bool PS2::synaptics_identify(uint8_t &minor, uint8_t &model_code, uint8_t &major) {
    // Sequence: Set Resolution to 0 four times, then Status Request
    for (int i = 0; i < 4; i++) {
        if (!command(PS2_CMD_SET_RES, 0x00)) return false;
    }
    
    flush_rx();
    if (!send_byte(PS2_CMD_STATUS_REQ)) return false;

    uint8_t resp[3];
    // ACK
    if (!recv_byte(resp[0], 200) || resp[0] != PS2_ACK) return false;
    
    // Read 3 status bytes
    for (int i = 0; i < 3; i++) {
        if (!recv_byte(resp[i], 200)) return false;
    }

    // Synaptics signature is 0x47 in the middle byte
    if (resp[1] != 0x47) {
        return false;
    }

    minor = resp[0];
    major = resp[2] & 0x0F;
    model_code = (resp[2] >> 4) & 0x0F;
    
    return true;
}

// ---------------------------------------------------------------------------
// synaptics_set_mode — Write Synaptics mode byte using E8 sequence
// ---------------------------------------------------------------------------

bool PS2::synaptics_set_mode(uint8_t mode_byte) {
    // Mode byte is split into four 2-bit chunks, sent as resolution commands
    uint8_t chunks[4];
    chunks[0] = (mode_byte >> 6) & 0x03;
    chunks[1] = (mode_byte >> 4) & 0x03;
    chunks[2] = (mode_byte >> 2) & 0x03;
    chunks[3] = (mode_byte >> 0) & 0x03;

    for (int i = 0; i < 4; i++) {
        if (!command(PS2_CMD_SET_RES, chunks[i])) return false;
    }

    // Set Sample Rate to 20 (0x14) to commit the mode byte
    if (!command(PS2_CMD_SET_RATE, 0x14)) {
        return false;
    }

    // Update state flag (bit 7 of mode_byte enables absolute mode)
    is_synaptics_absolute_ = (mode_byte & 0x80) != 0;
    
    return true;
}

// ---------------------------------------------------------------------------
// read_synaptics_packet — Read and decode a 6-byte Absolute Mode packet
//
// Format (W mode enabled):
// B0: 1 0 W3 W2 0 W1 R L
// B1: Y11 Y10 Y9 Y8 X11 X10 X9 X8
// B2: Z7 Z6 Z5 Z4 Z3 Z2 Z1 Z0
// B3: 1 1 Y12 X12 0 W0 D U
// B4: X7 X6 X5 X4 X3 X2 X1 X0
// B5: Y7 Y6 Y5 Y4 Y3 Y2 Y1 Y0
// ---------------------------------------------------------------------------

bool PS2::read_synaptics_packet(SynapticsData &data, uint32_t timeout_ms) {
    uint8_t buf[6];

    if (!recv_byte(buf[0], timeout_ms)) {
        return false;
    }

    // Validate sync bit: Bit 7 of byte 0 should be 1.
    if ((buf[0] & 0x80) == 0) {
        static constexpr int MAX_RESYNC = 24;
        bool synced = false;
        for (int i = 0; i < MAX_RESYNC; i++) {
            uint8_t candidate;
            if (!recv_byte(candidate, timeout_ms)) {
                return false;
            }
            if (candidate & 0x80) {
                buf[0] = candidate;
                synced = true;
                printf("[PS2] Synaptics Resync: skipped %d byte(s)\n", i + 1);
                break;
            }
        }
        if (!synced) {
            flush_rx();
            printf("[PS2] Synaptics Resync failed — flushed RX FIFO\n");
            return false;
        }
    }

    // Read remaining 5 bytes
    for (int i = 1; i < 6; i++) {
        if (!recv_byte(buf[i], timeout_ms)) {
            return false;
        }
    }

    // Secondary sync check on byte 3: bits 7 and 6 are usually 1 1 or 1 0.
    // If bit 7 of byte 3 is 0, we might be out of sync.
    if ((buf[3] & 0x80) == 0) {
        // Just let the next loop iteration resync
        return false;
    }

    // Extract X and Y (13 bits each)
    data.x = buf[4] | ((buf[1] & 0x0F) << 8) | (((buf[3] >> 4) & 0x01) << 12);
    data.y = buf[5] | (((buf[1] >> 4) & 0x0F) << 8) | (((buf[3] >> 5) & 0x01) << 12);
    
    // Extract Z (Pressure)
    data.z = buf[2];

    // Extract W (Finger count / width)
    data.w = ((buf[0] & 0x30) >> 2) | ((buf[0] & 0x04) >> 1) | ((buf[3] & 0x04) >> 2);

    // Extract Buttons
    data.left  = buf[0] & 0x01;
    data.right = (buf[0] >> 1) & 0x01;
    data.up    = buf[3] & 0x01;
    data.down  = (buf[3] >> 1) & 0x01;

    return true;
}
